sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR=$HOME/.composer/vendor/bin

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.3
      env: WP_VERSION=latest

install:
  - phpenv config-rm xdebug.ini
  - composer global require wp-cli/wp-cli
  - composer install --no-dev
  - bash bin/install-package-tests.sh

before_script:
  - composer validate

script:
  - behat --format progress --strict
