version: 2
jobs:
  build:
    working_directory: ~/wp-cli/package-tests
    parallelism: 1
    docker:
    - image: circleci/php:7.1
    - image: circleci/mysql:5.6
      environment:
        MYSQL_HOST: 127.0.0.1
        MYSQL_DB: wp_cli_test
        MYSQL_USER: wp_cli_test
        MYSQL_PASSWORD: password1
    steps:
    - checkout
    - run: |
        composer require wp-cli/wp-cli:dev-master
        composer install
    - run: |
        echo 'export PATH=$HOME/wp-cli/package-tests/vendor/bin:$PATH' >> $BASH_ENV
        source $BASH_ENV
    - run: |
        composer validate
        WP_VERSION=latest bash bin/test.sh
        rm -rf '/tmp/wp-cli-test core-download-cache'
        WP_VERSION=trunk bash bin/test.sh
