version: 2
jobs:
  build:
    working_directory: ~/wp-cli/package-tests
    parallelism: 1
    docker:
    - image: circleci/php:7.1
    steps:
    - checkout
    - run: |
      composer require wp-cli/wp-cli:dev-master
      composer install
      bash bin/install-package-tests.sh
    - run: |
      composer validate
      WP_VERSION=latest bash bin/test.sh
      rm -rf '/tmp/wp-cli-test core-download-cache'
      WP_VERSION=trunk bash bin/test.sh
